config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show]
  resources :posts, except: [:destroy] do
    resources :comments, only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy, :index]

root 'static_pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :user_id, presence: true
  validates :body, presence: true, length: { maximum: 500 }
  validates :post_id, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :user_id, presence: true
	validates :body, presence: true, length: { minimum: 10 }
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

	belongs_to :invited_user, class_name: "User", foreign_key: :invited_id
	belongs_to :inviting_user,  class_name: "User", foreign_key: :inviting_id
end

app/models/user.rb
class User < ActiveRecord::Base
  
	has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :sent_invites, class_name: "Relationship", foreign_key: :inviting_id, dependent: :destroy
  has_many :received_invites, class_name: "Relationship", foreign_key: :invited_id, dependent: :destroy

  has_many :invited_users, through: :sent_invites, source: :invited_user
  has_many :inviting_users, through: :received_invites, source: :inviting_user 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def full_name
  		name.blank? ? email : name
  end

  def feed
    followed_ids = "SELECT invited_id FROM relationships
                     WHERE  inviting_id = :user_id"
    Post.where("user_id IN (#{followed_ids})
                     OR user_id = :user_id", user_id: id)
  end

  

  protected
  def confirmation_required?
  	false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password,
             :current_password, :date_of_birth, :email_notification ) }
        end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authenticate_user!, only: [:create, :destroy]

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.build(comment_params)
		@comment.user_id = current_user.id
		if @comment.save
			if (@comment.user_id != @post.user_id) && (@post.user.email_notification == true)
				UsersMailer.new_comment_email(@comment).deliver
			end
			flash[:success] = "Created new comment"
			redirect_to @post
		else
			flash[:danger] = "Something went wrong"
			redirect_to @post
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find params[:id]
		if @comment.user_id == current_user.id
			@comment.destroy
			flash[:success] = "Comment deleted"
		else
			flash[:danger] = "You can't do this!"
		end
		redirect_to @post
		
	end


	private

	def comment_params
		params.require(:comment).permit(:post_id, :body)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authenticate_user!, except: [:index, :show]
	before_filter :find_post, only: [:show, :edit, :update]

	def index
		@posts = Post.order('created_at DESC').page(params[:page]).per(10)
	end

	def show
	end

	def new
		@post = Post.new
	end

	def create 
		@user = current_user
		@post = @user.posts.build(allowed_params)

		if @post.save
			flash[:success] = "Created new post"
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		redirect_to posts_path unless @post.user == current_user
	end

	def update
		if @post.user == current_user
			if @post.update_attributes(allowed_params)
				flash[:success] = "Updated post"
				redirect_to @post
			else
				render "edit"
			end
		else
			redirect_to posts_path
			flash[:notice] = "You can't do this"
		end
	end

	private
		def allowed_params
			params.require(:post).permit(:body)
		end

		def find_post
			@post = Post.find(params[:id])
		end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	before_filter :authenticate_user!

	def create
	    @invited_user = User.find(params[:relationship][:invited_id])
	    if (@invited_user != current_user)
		    @relationship = current_user.sent_invites.build(invited_id: @invited_user.id)

		    if @relationship.save
		        flash[:success] = "Successfully invited"
		        redirect_to @invited_user
		    else
		        flash[:danger] = "Unsuccessful"
		        redirect_to users_path
		    end
		else
			redirect_to users_path
			flash[:danger] = "You cannot follow yourself"
		end
	end

	def destroy
	  @relationship = Relationship.find(params[:relationship][:relationship_id])
	  @inviting_user = User.find(@relationship.inviting_id)
	  if @inviting_user == current_user
	    @relationship.destroy
	    flash[:success] = "Removed relationship"
	  end
	  redirect_to @relationship.invited_user
	end

	def index
	    @sent_invites = current_user.sent_invites.order('created_at DESC').page(params[:page]).per(10)
	    @received_invites = current_user.received_invites.order('created_at DESC').page(params[:page]).per(10)
	end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	

	def home
		if current_user
			@feed_items = current_user.feed.order('created_at DESC').page(params[:page]).per(10)
		end
	end	

	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!, only: [:index, :show]
	def index
		@users = User.order('created_at DESC').page(params[:page]).per(10)
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts.order('created_at DESC').page(params[:page]).per(10)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# returns the full title
	def full_title(page_title = "")
		base_title = "Ruby on Rails Exercise App"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end

	# checks if the post in the feed is writen by current_user
	def feed_post_style(post)
	    post.user_id == current_user.id ? "my_post" : "other_post"
  	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="panel panel-default comment">
	<div class="panel-body comment_content">
		<% if current_user && comment.user_id == current_user.id %>
			<p class="delete_comment">
				<%= link_to "Delete", [@post, comment], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default btn-xs btn-delete" %>  
			</p>
		<% end %>
		<p class="comment_body"><%= comment.body %></p>
		<p class="commenter">
			<small>
				<strong>By: </strong>
					<%= link_to comment.user.full_name, user_path(comment.user)  %>
			</small>
		</p>
		<p class="date comment_time"><%= comment.created_at.strftime("%R |  %F") %></p>
	</div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<%= render "shared/error_messages", object: f.object %>
	<div class="form-group">
		<%= f.text_area :body, class: "form-control" %>
	</div>

	<%= f.submit "Submit", class: "btn btn-default", data: { disable_with: 'Submitting...' } %>
<% end %> 

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
	    <div class="alert alert-<%= message_type %> alert-dismissable">
	        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	        <%= message %>
	    </div>
<% end %>

<script>
    $('.alert').fadeOut(4500);
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "Exercise App", root_path, class: 'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">

            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to 'Posts', posts_path %></li>
                <li><%= link_to 'Users', users_path %></li>
                 

                <% if current_user %>
                    <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                    <li><%= link_to 'Relationships', relationships_path %></li>

                    <li><%= link_to 'My Profile', user_path(current_user) %> </li>
                    <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to 'Login', new_user_session_path %></li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
	<%= render 'layouts/flash_messages' %>
	<%= render 'layouts/header' %>
	
	<div class="container">
		<%= yield %>
	</div>
	<%= render 'shared/google_analytics' %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for post do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="form-group">
        <%= f.label :body, class: "control-label" %>
        <%= f.text_area :body, class: "form-control", rows: 6 %>
    </div>

    <%= f.submit 'Save', class: "btn btn-default" %>
<% end %>

app/views/posts/edit.html.erb
<% provide(:title, "Edit post") %>
<p><%= link_to "Back", post_path(@post) %> </p>
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<% provide(:title, "Posts") %>
<div class="row posts-list">
	<%= link_to 'New Post', new_post_path, class: "btn btn-default btn-lg center-block" %>
	<h1>This is a list of posts</h1>
	
	
	<%= paginate(@posts) %>
	<% @posts.each do |post| %>
		<div class="panel panel-default <%= feed_post_style(post) %>">
			<%= link_to post_path(post) do %>
				<div class="panel-body">
					<p><%= post.body %> </p>
					<p><small><strong>By: </strong><%= link_to post.user.full_name, user_path(post.user) %></small></p>
					<p class="date"><%= "Posted at " + post.created_at.strftime("%R |  %F") %></p>
					<%= content_tag(:p,  ("Last updated at " + post.updated_at.strftime("%R |  %F")),
					 class: "date",) unless ((post.created_at) == (post.updated_at)) %>

				</div>
			<% end %>
		</div>
	<% end %>
	<%= paginate(@posts) %>
</div>

app/views/posts/new.html.erb
<% provide(:title, "New post") %>
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<% if @post.user ==current_user %>
			<small class="edit-link"><%= link_to "Edit", edit_post_path(@post), class: "btn btn-default btn-xs" %></small>
		<% end %>
		<p><%= @post.body%></p>
		<p><small><strong>By: </strong><%= link_to @post.user.full_name, user_path(@post.user) %></small></p>
		<p class="date"><%= "Posted at " + @post.created_at.strftime("%R |  %F") %></p>
		<%= content_tag(:p,  ("Last updated at " + @post.updated_at.strftime("%R |  %F")),
					 class: "date",) unless ((@post.created_at) == (@post.updated_at)) %>
	</div>
</div>

<h2><%= pluralize(@post.comments.count, 'comment') %> </h2>
<div class="comments">
	
	<%= render @post.comments %>

<% if user_signed_in? %>
	<%= render "comments/form" %>
<% else %>
	<h3>You have to <%= link_to 'login', new_user_session_path %> to comment</h3>
<% end %>
</div>

app/views/relationships/index.html.erb
<% provide(:title, "Relationships") %>
<div class="row">
  <div class="sent_invites col-sm-5 col-md-5">
    <div class="users-list">
      <% if @sent_invites.any? %>
        <h3 style="text-align: center">Invited user</h3>
        <div class="users row">
          <% @sent_invites.each do |invitation| %>
            <div class="panel panel-default">
              <%= link_to user_path(invitation.invited_user) do %>
                <div class="panel-body">
                  <p><%= invitation.invited_user.full_name %></p>
                </div>
              <% end %>
            </div>
          <% end %>
          <%= paginate(@sent_invites) %>
        </div>
      <% else %>
        <h3> You aren't following any user </h3> 
      <% end %>
    </div>
  </div>

  <div class="received_invites col-md-5 col-sm-5">
    <div class="users-list">
      <% if @received_invites.any? %>
        <h3 style="text-align: center">Invitations received</h3>
        <div class="users row">
          <% @received_invites.each do |invitation| %>
            <div class="panel panel-default">
              <%= link_to user_path(invitation.inviting_user) do %>
                <div class="panel-body">
                  <p><%= invitation.inviting_user.full_name %></p>
                </div>
              <% end %>
            </div>
          <% end %>
          <%= paginate(@received_invites) %>
        </div>
      <% else %>
        <h3> You aren't followed by any user </h3>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <p><strong>This form contains <%= pluralize(object.errors.count, 'errors') %>.</strong></p>
            <ul>
                <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>

    <script>
    $('#error_explanation').fadeOut(6500);
    </script>
<% end %>

app/views/shared/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV["google_analytics_code"] %>', 'auto');
  ga('send', 'pageview');

</script>

app/views/static_pages/home.html.erb
<% if current_user %> 
	
	<div class="row profile">
		<div class="col-sm-4 col-md-3 user-info">
			<%= link_to "Create new post!", new_post_path, class: "btn btn-lg btn-default", style:"margin-left:auto; margin-right:auto; width:100%" %>
			<h3><%= current_user.full_name %></h3>
				<ul>
					<%= content_tag(:li, ("Name: " + current_user.name)) unless  current_user.name.blank? %>
					<%= content_tag(:li, ("Age: " + distance_of_time_in_words(Time.now, current_user.date_of_birth) + " old")) unless current_user.date_of_birth.blank? %>
				</ul>
				<% if current_user.sent_invites.any? %>
					<p>You are following <%=  pluralize(current_user.sent_invites.count, 'user') %> </p>
				<% else %>
					<p> You aren't following any user </p>	
				<% end %>

				<% if current_user.received_invites.any? %>
					<p>You are followed by <%= pluralize(current_user.received_invites.count, 'user') %></p>
				<% else %>
					<p> You aren't followed by any user </p>
				<% end %>
		</div>
		<div class="user-feed col-sm-8 col-md-9">
			<%= paginate(@feed_items) %>
			<% @feed_items.each do |post| %>
				<div class="panel panel-default <%= feed_post_style(post) %>">
					<%= link_to post_path(post) do %>
						<div class="panel-body">
							<%= post.body %>
							<p><small><strong>By: </strong><%= link_to post.user.full_name, user_path(post.user) %></small></p>
							<p class="date"><%= "Posted at " + post.created_at.strftime("%R | %F") %></p>
							<%= content_tag(:p,  ("Last updated at " + post.updated_at.strftime("%R |  %F")),
						 class: "date",) unless ((post.created_at) == (post.updated_at)) %>
						</div>
					<% end %>
				</div>
			<% end %>
			<%= paginate(@feed_items) %>
		</div>
	</div>

<% else %>
	<div class="center jumbotron">
    	<h1>Welcome to the Exercise App</h1>
    	<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-default" %>
    </div>
<% end %>

app/views/users/index.html.erb
<% provide(:title, "Users") %>
<div class="users-list">
	<h1 class>This is a list of users</h1>
	<div class="users row">
		<%= paginate(@users) %>
		<% @users.each do |user| %>
		<div class="panel panel-default">
			<%= link_to user_path(user) do %>
				<div class="panel-body">
					<p><%= user.full_name %></p>
				</div>
			<% end %>
		</div>
		<% end %>
		<%= paginate(@users) %>
	</div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<% provide(:title, @user.full_name) %>
<div class="row profile">
	<div class="col-sm-4 col-md-3 user-info">
		<h3><%= @user.full_name %></h3>

		<% if current_user && current_user != @user%>

			<% @relationship = current_user.sent_invites.where(invited_id: @user.id).first %>

			<% if @relationship %>
				<%= form_for :relationship, url: relationship_path,  html: { method: :delete } do |f| %>
					<%= f.hidden_field :relationship_id, value: @relationship.id %>
			  		<%= f.submit "Unfollow", class: 'btn btn-default' %>
			  	<% end %>
			<% else %>
			  <%= form_for :relationship, url: relationships_path, html: { method: :post } do |f| %>
			    <%= f.hidden_field :invited_id, value: @user.id %>
			    <%= f.submit 'Follow', class: 'btn btn-default' %>
			  <% end %>
			<% end %>
		<% end %>

		<ul>
			<%= content_tag(:li, ("Name: " + @user.name)) unless  @user.name.blank? %>
			<%= content_tag(:li, ("Age: " + distance_of_time_in_words(Time.now, @user.date_of_birth) + " old")) unless @user.date_of_birth.blank? %>
		</ul>
	</div>
	<div class="user-posts col-sm-8 col-md-9">
		<%= paginate(@posts) %>
		<% @posts.each do |post| %>
			<div class="panel panel-default">
				<%= link_to post_path(post) do %>
					<div class="panel-body">
						<%= post.body %>
						<p class="date"><%= "Posted at " + post.created_at.strftime("%R | %F") %></p>
						<%= content_tag(:p,  ("Last updated at " + post.updated_at.strftime("%R |  %F")),
					 class: "date",) unless ((post.created_at) == (post.updated_at)) %>
					</div>
				<% end %>
			</div>
		<% end %>
		<%= paginate(@posts) %>
	</div>
</div>